### ISSUE TITLE
I got this issue same, do you have resolve for it?

### ISSUE THREAD

**Issue by gioxoay** [shortpoet/vite-ts-docker#1]
I got this issue same, do you have resolve for it? Thank you!

**Comment by gioxoay** [comment]
I found reason for this issue, esbuild not working as expected if version great than 0.6.28, then add this one into packages.json
```
"resolutions": {
    "vite/esbuild": "0.6.28"
  }
```

**Comment by brmdbr** [comment]
@gioxoay Thanks for sharing! I got the same issue but your solution doesn't seem to do it. Can you share your code so I can see what we do different?

**Comment by gioxoay** [comment]
Hi @brmdbr,
I added this one into package.json
```
"resolutions": {
    "vite/esbuild": "0.6.28"
}
```
And use yarn then all are well.

**Comment by brmdbr** [comment]
This is the error I get then, any suggestions maybe?

```
$ vite build --mode production
vite v1.0.0-rc.4
/app/client/node_modules/esbuild/bin/esbuild:2
throw new Error(`esbuild: Failed to install correctly`);
^

Error: esbuild: Failed to install correctly
    at Object.<anonymous> (/app/client/node_modules/esbuild/bin/esbuild:2:7)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
[vite] error while transforming /app/client/vite.config.ts with esbuild:
Error: The service was stopped
    at /app/client/node_modules/esbuild/lib/main.js:405:31
    at Socket.afterClose (/app/client/node_modules/esbuild/lib/main.js:331:7)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1252:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
- Building for production...

[vite] Build errored out.
Error: Could not resolve entry module (index.html).
    at error (/app/client/node_modules/rollup/dist/shared/rollup.js:5210:30)
    at ModuleLoader.loadEntryModule (/app/client/node_modules/rollup/dist/shared/rollup.js:18295:16)
    at async Promise.all (index 0) {
  code: 'UNRESOLVED_ENTRY'
}
error Command failed with exit code 1.
```

**Comment by brmdbr** [comment]
Got it working using the node:14-buster-slim image
